version: '3.8'

services:
  allure:
    image: "frankescobar/allure-docker-service"
    user: 1000:1000
    environment:
      TLS: 1
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 3
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports

      - ./allure-results:/app/projects/2/results
      - ./allure-reports:/app/projects/2/reports



  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"